name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check files
        run: echo "Workflow fayli muvaffaqiyatli yuklandi!"